export const homeCopy = {
  en: {
    pageTitle: 'Keyboard-first DeepSeek coding agent',
    heroText: 'Into the Unknown',
    tagline: 'omdsh is a focused, keyboard-first DeepSeek coding agent for your terminal, built on the DeepSeek Harness plugin runtime.',
    actionPrimary: 'Get Started',
    actionAlt: 'View on GitHub',
    installHeading: 'Install',
    installNote: 'Requires Node.js 22.19 or later in the 22.x line, or Node.js 24 or newer, plus a DeepSeek API key. Run /login once inside omdsh, then start a conversation.',
    featuresHeading: 'What a turn looks like',
    features: [
      {
        handle: '/sessions',
        title: 'Durable conversations',
        details: 'Search, pin, rename, and resume sessions; rewind turns, retry, compact context, and export complete transcripts as Markdown or standalone HTML.',
        href: '/docs/tutorials/long-session',
      },
      {
        handle: '/agent /workflow /permission',
        title: 'Three real session controls',
        details: 'Choose an Agent preset, a Default or Plan workflow, and an Access level per session. Each preset owns its tool exposure, so the model never carries capabilities the session did not grant.',
        href: '/docs/tutorials/first-task',
      },
      {
        handle: '@mention · Ctrl+V',
        title: 'Rich terminal input',
        details: 'Mention project files and sessions with @, paste clipboard images, reuse persistent prompt history, compose multiline prompts in $EDITOR, and queue follow-ups.',
        href: '/docs/tutorials/precise-context',
      },
      {
        handle: 'Alt+A',
        title: 'Subagents on a leash',
        details: 'Watch streaming tool calls and live child agents, open a child transcript in place, follow or steer continuable runs, and keep heavy parallel delegation off the render loop.',
        href: '/docs/tutorials/guide-a-turn',
      },
      {
        handle: '/trajectory · /context',
        title: 'Whole-session observability',
        details: 'Walk a keyboard-driven event ledger with live following, search, folding, timings, token usage, and tool payloads; /context separates provider-anchored occupancy from heuristic prompt composition.',
        href: '/docs/architecture',
      },
      {
        handle: 'Skills · MCP · plugins',
        title: 'Extend everything',
        details: 'Add project Skills and MCP servers from plain configuration, mount user plugin bundles with omdsh plugin, and drive local language servers through the read-only lsp tool.',
        href: '/docs/skills-and-mcp',
      },
    ],
    whyHeading: 'Why omdsh',
    why: [
      {
        handle: 'plugin architecture',
        title: 'Harness-native, not a fork',
        details: 'Sessions, models, tools, permissions, Skills, MCP servers, and telemetry come from published DeepSeek Harness services. omdsh composes them into one terminal application instead of building a second agent core.',
        href: '/docs/architecture',
      },
      {
        handle: 'keyboard-first',
        title: 'Every flow has a key',
        details: 'Queue follow-ups, steer a running child, search prompts and the transcript, switch model or Access, and export a session without leaving the composer.',
        href: '/docs/tutorials',
      },
      {
        handle: 'display cells',
        title: 'Built for real terminals',
        details: 'Layout is measured in terminal display cells, so CJK text, emoji, ANSI styling, and long commands keep borders and right padding aligned while the terminal keeps its own scrollback.',
        href: '/docs/performance',
      },
    ],
    proofHeading: 'Performance',
    proof: [
      { value: '2.62 ms', label: 'median restore of a 10,000-turn session' },
      { value: '22.71 ms', label: 'replay of 10,000 tool calls' },
      { value: '0.35 ms', label: 'average frame over a 5,000-turn surface' },
    ],
    proofNote: 'Median figures measured on Apple M5 Pro on the documented benchmark surface. The TUI performance report carries the methodology and raw results:',
    proofLink: 'TUI performance report',
    proofHref: '/docs/performance',
    keyboardHint: 'This site is keyboard-first too: press Ctrl+K to search, / works as well.',
  },
  zh: {
    pageTitle: '键盘优先的 DeepSeek 终端编程智能体',
    heroText: '探索未至之境',
    tagline: 'omdsh 是一个专注、键盘优先的 DeepSeek 终端编程智能体，构建于 DeepSeek Harness 插件运行时之上。',
    actionPrimary: '快速上手',
    actionAlt: 'GitHub 仓库',
    installHeading: '安装',
    installNote: '需要 Node.js 22.19 或更高的 22.x 版本，或者 Node.js 24 及更高版本，以及一个 DeepSeek API Key。在 omdsh 中运行一次 /login，即可开始对话。',
    featuresHeading: '一个回合里有什么',
    features: [
      {
        handle: '/sessions',
        title: '持久化对话',
        details: '搜索、置顶、重命名和恢复会话；回退回合、重试、压缩上下文，并把完整转录导出为 Markdown 或独立 HTML。',
        href: '/docs/tutorials/long-session',
      },
      {
        handle: '/agent /workflow /permission',
        title: '三项真实会话控制',
        details: '按会话选择 Agent preset、Default 或 Plan workflow、以及 Access 级别。工具暴露由 preset 决定，模型不会带上会话未授予的能力。',
        href: '/docs/tutorials/first-task',
      },
      {
        handle: '@mention · Ctrl+V',
        title: '丰富的终端输入',
        details: '用 @ 提及项目文件与会话、粘贴剪贴板图片、复用持久输入历史、在 $EDITOR 中编写多行提示，并排队后续消息。',
        href: '/docs/tutorials/precise-context',
      },
      {
        handle: 'Alt+A',
        title: '可引导的子智能体',
        details: '跟踪流式工具调用与实时的子智能体；就地打开子转录、跟进或引导可继续的运行，并把重度并行委派移出渲染循环。',
        href: '/docs/tutorials/guide-a-turn',
      },
      {
        handle: '/trajectory · /context',
        title: '全会话可观测',
        details: '打开键盘驱动的轨迹账本，支持实时跟随、搜索、折叠、耗时、Token 用量与工具载荷；/context 区分 provider 记账的占用与启发式提示组成。',
        href: '/docs/architecture',
      },
      {
        handle: 'Skills · MCP · plugins',
        title: '可扩展的一切',
        details: '用纯配置加入项目 Skills 与 MCP 服务器，用 omdsh plugin 挂载用户插件包，并通过只读 lsp 工具驱动本地语言服务器。',
        href: '/docs/skills-and-mcp',
      },
    ],
    whyHeading: '为什么选择 omdsh',
    why: [
      {
        handle: '插件架构',
        title: '原生 Harness，而非分叉',
        details: '会话、模型、工具、权限、Skills、MCP 服务器与遥测都来自已发布的 DeepSeek Harness 服务；omdsh 把它们组合成一个终端应用，而不是再造一个 agent 内核。',
        href: '/docs/architecture',
      },
      {
        handle: '键盘优先',
        title: '每个流程都有按键路径',
        details: '排队后续消息、引导正在运行的子智能体、搜索输入历史与转录、切换模型或 Access、导出会话，全程不必离开 composer。',
        href: '/docs/tutorials',
      },
      {
        handle: '显示单元格',
        title: '为真实终端而构建',
        details: '布局以终端显示单元格度量，CJK 文本、emoji、ANSI 样式与超长命令下边框和右侧留白依然对齐，同时保留终端自身的滚动回看。',
        href: '/docs/performance',
      },
    ],
    proofHeading: '性能',
    proof: [
      { value: '2.62 ms', label: '恢复 10,000 回合会话的中位耗时' },
      { value: '22.71 ms', label: '回放 10,000 次工具调用' },
      { value: '0.35 ms', label: '5,000 回合界面上的平均每帧渲染' },
    ],
    proofNote: '以上为文档所载 Apple M5 Pro 基准环境的中位数，测试方法与原始结果见 TUI 性能报告：',
    proofLink: 'TUI 性能报告',
    proofHref: '/docs/performance',
    keyboardHint: '本站同样键盘优先：按 Ctrl+K 搜索，/ 也可以。',
  },
} as const
